GET http://localhost:3000/students

###
GET http://localhost:3000/students/3

###

POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Schluribumbu",
  "course": "Ruh geben"
}

###
DELETE http://localhost:3000/students/2
