GET http://localhost:3000/students

###
GET http://localhost:3000/students/3

###
POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Schluribumbu",
  "course": "Ruh geben"
}

###
PATCH http://localhost:3000/students/1
Content-Type: application/json

{
  "name": "Annalisa",
  "course": "Ruh geben"
}

###
DELETE http://localhost:3000/students/2

### setzt den cookie usw...
POST http://localhost:3000/login
Content-Type: application/json

{
  "user": "versuchsanstalt",
  "pass": "wiederfalsch"
}

###
POST http://localhost:3000/chkpass
Content-Type: application/json

{
  "user": "admin",
  "pass": "admin"
}

### Das funktioniert, wenn das Passwort richtig ist:
POST https://grafg1.spengergasse.at/verify
Content-Type: application/json

{
  "user": "versuchsanstalt",
  "passwd": "falschesPasswort"
}

